spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/droplite
    username: droplite
    password: droplite_password
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# File Storage Configuration
file:
  storage:
    upload-dir: uploads

# Logging
logging:
  level:
    org.springframework.web: INFO
    com.droplite: DEBUG
